### ISSUE TITLE
Images should be resized

### ISSUE THREAD

**Issue by youdang** [kimcc/hugo-theme-noteworthy#9]
Large images are not supported well, and should be resized to fit in content.

Current:

![image](https://user-images.githubusercontent.com/953085/77314715-289e8280-6d41-11ea-885e-4b1cce9bf815.png)

Large images with `max-width` style:

![image](https://user-images.githubusercontent.com/953085/77314947-9f3b8000-6d41-11ea-8ad5-1c37f10fb0a7.png)

**Comment by nemo83** [comment]
How did you even insert an image? Did you use the ![tltle](/path/to/image)?

**Comment by kimcc** [comment]
@youdang Added a fix for this in the latest update. Now you can set the image to limit its size with the resize-image shortcode. Like this:
```
{{< resize-image src="image1.jpg" alt="My first image" >}}
```

@nemo83 Yes, you can insert images directly into the markdown file like that.

**Comment by nemo83** [comment]
Thanks @kimcc

**Comment by entron** [comment]
@kimcc First, thanks very much for the beautiful theme! I noticed there seems to have maximum value on the text width so that one would have a super long line even viewed on computer. This is very nice. I am wondering is there a way (e.g. changing css?) to automatically scale down the image if the image is larger than the text's maximu width? In this way I don't have to change all my posts to use the shortcode.
